version: "3.8"

services:
  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./auth-service:/app
    env_file:
      - ./auth-service/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: auth-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-auth_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
