version: "3.7"
services:
  auth-service:
    build:
      context: ./auth-service
      target: dev
    environment:
      - env=dev
      - GOPATH=/go
    working_dir: /app
    ports:
      - "${PORT_AUTH}:${PORT_AUTH}"
    volumes:
      - ./auth-service:/app:delegated
      - go-modules:/go/pkg/mod
    depends_on:
      - db-auth
    env_file:
      - auth-service/.env
    networks:
      - app-network

  db-auth:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER_AUTH}
      POSTGRES_PASSWORD: ${DB_PASSWORD_AUTH}
      POSTGRES_DB: ${DB_NAME_AUTH}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  go-modules:
