version: "3.7"
services:
  auth-service:
    build:
      context: ./auth-service
      target: dev
    environment:
      - ENV=dev
      - GOPATH=/go
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./auth-service:/app:delegated
      - go-modules:/go/pkg/mod
    depends_on:
      - db
    env_file:
      - auth-service/.ENV
    networks:
      - app-network

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  go-modules:
