# Image Go base
FROM golang:1.24-alpine

RUN apk update && apk add --no-cache git curl bash

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY . .

RUN go mod tidy

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
